sudo: required
dist: trusty
addons:
  apt:
    packages:
    - texlive-xetex
    - texlive-latex-extra
    - lmodern
    - texlive-latex-recommended
    - xzdec
    - texlive-fonts-recommended
script:
- tlmgr init-usertree
- tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
- tlmgr update --all
- tlmgr install etoolbox tcolorbox framed polyglossia hyperref pgf xcolor
- xelatex bsz1.tex
- xelatex bsz1.tex
deploy:
  provider: releases
  api_key:
    secure: HBft8Useq08g3qMWq5s/Tfbm/1ke7SxVhAJZy+gV69qAUtIqvfUN+zE7TsE8RtKIuHTFlTW8x9zplKsXVZlq8KrqkRt/nsDwzDjPY4GMbe6l2DatVOTdStTzEhyMurBqbfyLzUBkthOaLAyIrGmpFWCbkIvEeutwVzeNDi6QRPd6nosOrVNTeYY/tgqaLiJHv42AlJ0TeyF1QLCwv3ER5qVWVo7GT9IdTPBGoo1a+VKgGPbnrM+tIFxOTnYaCJpQFx8NXDvv54LrJ8RB2e65zAzQZsXj4CEQZBZ+1BeifOEp7eWy66wadJYF8DNNZWqhV0zjY2hZxelv4OTrkFLdFsWNGnXw/QsRuHKCLkDsqoIqwpSW5tsh3aVRrg7ornTzOoHtOJUhObRTVXRzPHITwudMx2u2/thDlCIYkNNBCNQGqMH4nuj4P3KBsidAloL4vBdyb1FzCtqxxIFBFLG2yG7kqMXW/qD+9uPCEiPbmfQBhIdnPoG7G+I6o+yhTSvnoDWZxwE1yNMWRt3WOi+Wez1P25THjJ9Vw06JscpK97rI8zubxcxkasKKRMKPIZ86nNSoYfAtB02+zZlkrqkeCR1mEroHETv+VhIXQxM/8bEY/UHGd0IPEVsjEI42yZMr3MkazZkYlTgkwITEiJ9ymiXp0XemYdweR56u4eCLkJk=
  file: bsz1.pdf
  skip-cleanup: true
  overwrite: true
  on:
    repo: bme-notes/bsz1
